/* Generate a SCOPED nav stylesheet for the static course pages from the
   @readysetcloud/ui package styles.

   The course pages are self-contained apps with their own design system —
   their own `.btn`, `.card`, `--surface`, and bare `header`/`nav` rules. The
   package's browser AppNav (js/vendor/rsc-nav.global.js) emits the same markup
   the React <AppNav> does and expects the package's tokens + component classes.
   Loading the package's global stylesheet as-is would collide with every
   course's own classes and variables.

   So we transform the package's tokens.css + components.css into a stylesheet
   where EVERY rule is confined to the nav and its two modals:

       .app-nav              the top bar (rendered into #rsc-appnav)
       .app-launcher-modal   the "other RSC apps" dialog (appended to <body>)
       .profile-menu-modal   the signed-in profile dialog (appended to <body>)

   Package tokens are pinned to their DARK values on those three roots (the
   course pages are permanently dark). Nothing in the output can match an
   element outside the nav subtree, so the course UI is untouched.

   Run: node tools/build-nav-css.mjs <pkg-styles-dir> <out-css>
   The output is committed so the course pages need no build step at runtime. */

import { readFileSync, writeFileSync } from "node:fs";

const stylesDir = process.argv[2];
const outFile = process.argv[3];
if (!stylesDir || !outFile) {
  console.error("usage: node tools/build-nav-css.mjs <pkg-styles-dir> <out-css>");
  process.exit(1);
}

const ROOTS = [".app-nav", ".app-launcher-modal", ".profile-menu-modal"];
const stripComments = (css) => css.replace(/\/\*[\s\S]*?\*\//g, "");

/* Rewrite one selector so it can only match inside the nav subtree. */
function scopeSelector(sel) {
  sel = sel.trim();
  if (!sel) return [];
  // Already unique to the nav / its modals — leave as authored.
  if (/^\.(app-nav|app-launcher|profile-menu)/.test(sel)) return [sel];
  // The dialog roots ARE `.modal` (class="modal app-launcher-modal ...") — so
  // `.modal`, `.modal::backdrop`, `.modal[open]` must map onto the roots
  // themselves, not a descendant.
  if (/^\.modal(?![\w-])/.test(sel)) {
    const rest = sel.slice(".modal".length);
    return [`.app-launcher-modal${rest}`, `.profile-menu-modal${rest}`];
  }
  // Any other generic component class (.btn, .badge, …) is descendant-scoped
  // under each root.
  return ROOTS.map((r) => `${r} ${sel}`);
}

const scopeList = (list) => list.split(",").flatMap(scopeSelector).join(", ");

/* Walk rules at one nesting level, scoping selectors; recurse into @media. */
function transform(css) {
  let out = "";
  let i = 0;
  const n = css.length;
  while (i < n) {
    const brace = css.indexOf("{", i);
    if (brace === -1) break;
    const prelude = css.slice(i, brace).trim();
    let depth = 1;
    let j = brace + 1;
    while (j < n && depth > 0) {
      if (css[j] === "{") depth++;
      else if (css[j] === "}") depth--;
      j++;
    }
    const inner = css.slice(brace + 1, j - 1);
    if (prelude.startsWith("@keyframes")) {
      out += `${prelude} {${inner}}\n`; // keyframe names are rsc-* — keep verbatim
    } else if (prelude.startsWith("@media") || prelude.startsWith("@supports")) {
      out += `${prelude} {\n${transform(inner)}}\n`;
    } else if (prelude) {
      out += `${scopeList(prelude)} {${inner}}\n`;
    }
    i = j;
  }
  return out;
}

/* Dark token block, re-rooted onto the nav scopes. */
const tokens = stripComments(readFileSync(`${stylesDir}/tokens.css`, "utf8"));
const darkMatch = tokens.match(/:root\[data-theme=['"]dark['"]\]\s*\{([\s\S]*?)\n\}/);
if (!darkMatch) throw new Error("could not find the [data-theme='dark'] token block");
const darkTokens = `${ROOTS.join(",\n")} {\n${darkMatch[1]}\n}\n`;

/* Component rules, scoped. Asset URLs are relative to the CSS file, which now
   lives at js/vendor/ next to a vendored assets/ copy. */
const components = stripComments(readFileSync(`${stylesDir}/components.css`, "utf8"))
  .replace(/url\((['"]?)\.\.\/assets\//g, "url($1./assets/");

/* Course-page tailoring the package can't know about: the pages are dark-only,
   so the theme toggle is inert here — hide it. And keep box-sizing sane inside
   the nav without pulling in the package's global reset. */
const overrides = `
/* --- course-page overrides (not from the package) --- */
.app-nav *, .app-launcher-modal *, .profile-menu-modal * { box-sizing: border-box; }
/* dark-only pages: the light/dark toggle would be a no-op, so hide it */
.app-nav-actions > button[aria-label^="Switch to"] { display: none; }
`;

const banner = `/* GENERATED by tools/build-nav-css.mjs from @readysetcloud/ui styles.
   Do not edit by hand — re-run the tool to regenerate.
   Every rule here is scoped to .app-nav / .app-launcher-modal /
   .profile-menu-modal so it cannot touch the course pages' own styles. */\n\n`;

writeFileSync(outFile, banner + darkTokens + "\n" + transform(components) + overrides);
console.log(`wrote ${outFile}`);
